### ISSUE TITLE
Component Event Handling - Jira Report

### ISSUE THREAD

**Issue by pnispero** [eed-web-application/core-build-system#40]
# Component Event Handling - Jira Report
For every component, since each major event is being tracked for a branch (created PR, build/test report, merge PR), we want to report that on the corresponding Jira issue. Github Issues already does this automatically once a branch is associated with an issue, but we have to implement that functionality for Jira.
## TODO
- [ ] If a new PR is created, then get the issue from the branch name like `fix/EEDSWCM-39`, and use that to get the Jira issue, and add a comment saying `New PR created - <link here>`
- [ ] If a build/test is automatically done then report that to the issue
- [ ] If a PR is merged then report that to the issue
